version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - app_data:/app/data

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  app_data:
  db_data:
